spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/member?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: sa123
  druid:
    initialSize: 5
    maxActive: 20
    maxWait: 60000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 from DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
#配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
    filters: stat,wall,slf4j
#通过connectProperties属性来打开mergeSql功能;慢SQL记录
    connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'
#-------------------redis----------------------
#  zipkin:
#    base-url: http://localhost:9411
#  application:
#    name: dbutil

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#------------------mybatis-------------------------
#mybatis:
##  type-aliases-package: com.alex.erp.dbutil.um.entity
#  configuration:
#    map-underscore-to-camel-case: true
#    jdbc-type-for-null: NULL
#    lazy-loading-enabled: true
#    aggressive-lazy-loading: true
#    cache-enabled: true
#    call-setters-on-nulls: true
#  mapper-locations: classpath*:mybatis/*.xml


#------------------mybatis-plus-------------------------
mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*.xml
#  type-aliases-package: com.amor.base.domain  #扫描实体类,配置xml的别名
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #逻辑删除配置
      logic-not-delete-value: 1 #删除前
      logic-delete-value: 0  #删除后




