spring:
  datasource:
    activiti:
       url: jdbc:mysql://localhost:3306/member?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
       username: root
       password: sa123
       driverClassName: com.mysql.cj.jdbc.Driver
       type: com.alibaba.druid.pool.DruidDataSource
