server:
  port:
    8088

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  security:
    user:
      name: alex
      password: 123456