
spring:
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    locator:
      discovery:
        enabled: true
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0
# 注册中心
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  cloud:
    config:
      uri: http://localhost:8888
security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/auth/oauth/token
      user-authorization-uri: http://localhost:${server.port}/auth/oauth/authorize
      client-id: web
    resource:
      user-info-uri:  http://localhost:${server.port}/auth/api/member
      prefer-token-info: false

auth:
  clientID: zysfx
  clientSecret: user123
  checkTokenEndpointUrl: http://localhost:9999/auth/oauth/check_token