spring:
  application:
    name: service-bussiness
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8764

management:
  security:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

security:
  oauth2:
    resource:
      id: service-bussiness
      tokenInfoUri: http://localhost:9999/auth/oauth/check_token
      prefer-token-info: true
