
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/member?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: sa123
  druid:
    initialSize: 5
    maxActive: 20
    maxWait: 60000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 from DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
#配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
    filters: stat,wall,slf4j
#通过connectProperties属性来打开mergeSql功能;慢SQL记录
    connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'
#-------------------redis----------------------
  zipkin:
    base-url: http://localhost:9411
  application:
    name: authorizationServer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#------------------mybatis-------------------------
mybatis:
#  type-aliases-package: com.alex.erp.dbutil.um.entity
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    cache-enabled: true
    call-setters-on-nulls: true
  mapper-locations: classpath*:mybatis/*.xml




