server:
  port:
    8088
spring:
  application:
    name: config-server
  profiles:
    active: ci
    include: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  security:
    user:
      name: alex
      password: 123456
  rabbitmq:
      host: localhost
      port: 5672
      username: alex
      password: 123456
# 注册中心
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka/