server:
  port:
    8888
spring:
  application:
    name: config-server
  profiles:
    active: dev
    include: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  security:
    user:
      name: alex
      password: 123456
# 注册中心
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/