server:
  port: 8761
spring:
  application: 
    name: eurekaServer
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  security:
#    user:
#      name: alex
#      password: 123


#  security:
#    user:
#      name: alex
#      password: 123

